hide_window_decorations yes
include ~/.config/kitty/themes/Grape.conf
scrollback_lines 2000
font_size 18.0
font_family      Victor Mono
bold_font        Victor Mono
italic_font      Victor Mono
bold_italic_font Victor Mono
transparency=yes
background_opacity         0.8
dynamic_background_opacity yes
shell_integration no-cursor
cursor_shape block
