format = """
$directory\
$git_branch\
$git_status\
$c\
$python\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$ocaml\
$java\
$julia\
$lua\
$nodejs\
$nim\
$rust\
$package\
$scala\
$docker_context\
\n$character
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
vimcmd_symbol = "[<](bold green)"

[directory]
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
format = '[ $symbol ($version) ]($style)'

[docker_context]
format = '[ $symbol $context ]($style) $path'

[elixir]
format = '[ $symbol ($version) ]($style)'

[elm]
format = '[ $symbol ($version) ]($style)'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '[ $symbol ($version) ]($style)'

[gradle]
format = '[ $symbol ($version) ]($style)'

[haskell]
format = '[ $symbol ($version) ]($style)'

[java]
format = '[ $symbol ($version) ]($style)'

[julia]
format = '[ $symbol ($version) ]($style)'

[nodejs]
format = '[ $symbol ($version) ]($style)'

[nim]
format = '[ $symbol ($version) ]($style)'

[rust]
format = '[ $symbol ($version) ]($style)'

[ocaml]
format = '[ $symbol ($version) ]($style)'

[lua]
format = '[ $symbol ($version) ]($style)'

[python]
format = '[ $symbol ($version) ($virtualenv) ]($style)'

[package]
symbol = " "

[scala]
format = '[ $symbol ($version) ]($style)'
